package com.cmolina12.senehorario_backend.controller;

import com.cmolina12.senehorario_backend.domain.Section;
import com.cmolina12.senehorario_backend.service.ScheduleService;
import java.util.ArrayList; // Importing ArrayList to initialize an empty list of schedules if no schedules are generated.
import java.util.List; // Importing List to handle collections of sections in the schedule.
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/schedules")
public class ScheduleController {

    // This controller handles requests related to schedule generation based on course sections.
    @Autowired
    private ScheduleService scheduleService; // scheduleService is an instance of ScheduleService, which is used to generate schedules based on course sections.

    /**
     * Generates all possible schedules based on the provided list of lists of Section objects.
     *
     * @param candidates a list of lists of Section objects representing the course sections to consider for schedule generation.
     * @return a list of lists of Section objects representing all possible schedules generated by the ScheduleService.
     */

    @PostMapping
    public ResponseEntity<List<List<Section>>> getSchedules(
        @RequestBody List<List<Section>> candidates
    ) {
        List<List<Section>> schedules = scheduleService.generateAllSchedules(
            candidates
        ); // This method handles POST requests to /api/schedule, taking a list of lists of Section objects as input and returning all possible schedules generated by the ScheduleService.
        if (schedules == null) {
            schedules = new ArrayList<>(); // If no schedules are generated, it initializes an empty list to avoid returning null.
        }
        return ResponseEntity.ok(schedules); // If schedules are generated, it returns a 200 OK response with the list of schedules.
    }
}
